version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven:
        patterns:
          - "*:*"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
