version: 2
updates:
  # Patch-level updates (e.g., 1.1.x) will be merged into `main` automatically as a single MR
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 1 # Limit a single MR for all updates
    target-branch: "main"
    versioning-strategy: "increase-patch" 
    pull-request-branch-name: "dependabot/patch-updates"
    auto-merge: true
