/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.uftplib.service;

import org.junit.Test;
import static org.junit.Assert.*;

public class UftpSigningServiceImplementationTest {
    @Test public void testKeyGen() {
        UftpSigningServiceImplementation uftpSigningServiceImplementation = new UftpSigningServiceImplementation("AGR");
        var keyPair = uftpSigningServiceImplementation.generateKeyPair();
        System.out.println(keyPair.getPrivateKey());
        System.out.println(keyPair.getPublicKey());
        assertNotNull(keyPair);
    }


    @Test public void testSealMessage() {
        UftpSigningServiceImplementation uftpSigningServiceImplementation = new UftpSigningServiceImplementation("AGR");
        var sealedMessage = uftpSigningServiceImplementation.sealMessage("My Test Message", "pyKi39uRd2XU7LWsQiNwKS8ydvdbGyLH4gtj24weeVvtUcA5oqLBXzqRjPDKhQsxGM3Gipx9qDqjtAK8iygwrQ==", new DomainPair("xxx.com", "yyy.com"));
        System.out.println(sealedMessage);
        assertNotNull(sealedMessage);
    }

    @Test public void testUnsealMessage() {
        UftpSigningServiceImplementation uftpSigningServiceImplementation = new UftpSigningServiceImplementation("AGR");
        var unsealedMessage = uftpSigningServiceImplementation.unsealMessage("<SignedMessage Body=\"L0k3PN4Dpx2YicjfnQKCHNIbgev/jIXKmvSS61dzZ+pzGJATVCfGr+AVwzBXwFzTB9P+pSfmFvsygJvCYjXWAE15IFRlc3QgTWVzc2FnZQ==\" SenderDomain=\"xxx.com\" SenderRole=\"AGR\"/>", "7VHAOaKiwV86kYzwyoULMRjNxoqcfag6o7QCvIsoMK0=");
        System.out.println(unsealedMessage);
        assertNotNull(unsealedMessage);
    }


}
