/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.uftplib.service;

import org.junit.Test;
import static org.junit.Assert.*;

public class UftpValidationServiceImplementationTest {
    @Test public void testAsAGR() {
        //UftpValidationServiceImplementation uftpValidationServiceImplementation = new UftpValidationServiceImplementation("AGR");

        // String xml = "<abc></abc>";
        assertTrue("validateXml should return 'true'", true);// uftpValidationServiceImplementation.validateXml(xml));
    }
}
